commerce_payment.commerce_payment_gateway.plugin.novapay:
  type: commerce_payment_gateway_configuration
  label: 'NovaPay payment gateway configuration'

field.field.*.*.*.third_party.commerce_novapay:
  type: mapping
  label: 'Commerce NovaPay field settings'
  mapping:
    payment_phone:
      type: boolean
      label: 'Use this field as a NovaPay payment phone source'
